### PR TITLE
Add typedef support

### PR DESCRIPTION
**Pull request by Willyham**
@leizha @kriskowal 

I'd like to add typedef support before @jcorbin's refactor so that I can use them for my upcoming service.

### CODE REVIEW

**Comment by kriskowal** [comment]
This feature is not useful without support and tests for compound types.

`typedef set<string> strings`

**Comment by Willyham** [comment]
I agree that the full support for typedefs would be ideal, but if you take a look at the Uber codebase, 97% of 'typedef' statements are simple mappings to atomic types. :confused: 

Personally I think it would be better to take the pragmatic approach and cover that 97% of use cases - I can update this to throw a not implemented exception for types which aren't atomic.

**Comment by leizha** [comment]
I remember compound type support was already there. I was able to do `list<list<int>>`. do we have a regression or am I missing something here?

**Comment by kriskowal** [comment]
@leizha Compound types exist. I don’t think that compound types are addressable in the types object, last I checked.
@Willyham If people are aliasing atomics, sounds good to me to get this ball rolling.

**Comment by Raynos** [comment]
@Willyham a not implemented error for non-atomic types would be great

**Comment by Willyham** [comment]
Can I get another peek? I'd like to get this merged by my time tomorrow! Cheers

**Comment by Raynos** [comment]
@Willyham lgtm.

**Comment by leizha** [comment]
I think we should process typedef'd types in the same way as struct types. Can you remove `this.typedefs = {};` and just use `spec.setType(alias, type)`?

**Comment by Willyham** [comment]
Ah, ok I understand the code much better now. I've implemented the compound types now - very simple. :)

**Comment by leizha** [comment]
:+1:

**Pull request merged**
